name: Deploy
run-name: ${{ github.actor }} - ${{ github.repository }}


on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: Mercedes
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Comprobar Laravel
        run: |
          cd back/laravel
          composer update
          composer install
          cp .env.example .env
          php artisan key:generate
          php artisan migrate --seed
          php artisan test

      - run: echo "❤ Laravel OK ❤"