name: Deploy
run-name: ${{ github.actor }} - ${{ github.repository }}

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: Mercedes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Comprobar Laravel
        run: |
          cd back/laravel
          composer update
          composer install
          cp .env.example .env
          php artisan key:generate
          php artisan migrate --seed
          php artisan test

      - run: echo "❤ Laravel OK ❤"


  #     - name: Build Docker image
  #       run: |
  #         docker build -t my-nuxt-app .
  #         docker tag my-nuxt-app:latest my-nuxt-app:$(date +%s)
  #         echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  #         docker push my-nuxt-app

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to Docker Swarm
  #       run: |
  #         # Aquí pondrías los comandos necesarios para desplegar tu contenedor en Docker Swarm, Kubernetes u otro entorno de tu elección

